Sprint_11: Add database
FisanovE/java-filmorate pull request #10
Opened 2023-09-27 13:44 UTC by FisanovE

2023-09-28 05:30 UTC, krylov-sergey-sergeevich requested changes
Привет, очень неплохо, есть один вопрос давай его проработаем

2023-09-28 05:30 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +		return null;
Так и запланировано?

2023-09-28 11:00 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +	@Qualifier ("filmDbStorage")
Постараюсь не забыть!

2023-09-28 11:02 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/InMemoryFilmStorage.java
> +		return null;
Пропустил случайно, всё же эта реализация уже не актуальна. Исправил. Сделал реализацию пропущенных методов.

2023-09-29 05:25 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-09-29 12:28 UTC, merged