feat: создать приложение.
FisanovE/java-filmorate pull request #6
Opened 2023-08-13 19:31 UTC by FisanovE

Созданы две модели данных Film и User и два REST-контроллера для работы с ними. Созданы тесты для валидации полей моделей данных при их добавлении в контроллеры.

2023-08-13 20:51 UTC, FisanovE commented
Пытался сделать тесты REST-контроллеров через HTTP-запросы с валидацией полей через аннотации (пробный тест закоментирован в коде UserControllerTest). Но запросы не проходят, возвращается ошибка "415". Пришлось тестировать через экземпляры классов REST-контроллеров, а валидацию делать в методах. Валидация по аннотациям тоже работает, тесты из Постман проходят.

2023-08-14 18:54 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но давай поправим некоторые детали

- Текст исключений должен быть на англ языке
- Логов тоже желательно
- Избавиться  от дублей - вынести в методы повторяющиеся строки / блоки кода

2023-08-14 18:54 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Скидываю пример теста, чисто для ознакомления, не значит что надо переделывать:
```
import javax.validation.*;

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
validator = factory.getValidator();

@Test

public void invalidName() {

	film = Film.builder().name("")
	
			.description("qweq")
			
			.duration(120)
			
			.releaseDate(LocalDate.of(1999, 12, 12))
			
			.build();
	
	violations = validator.validate(film);
	
	  
	
	assertFalse(violations.isEmpty(), violations.toString());
	
	violations.clear();

}
```

2023-08-15 10:43 UTC, FisanovE commented
Привет, Сергей! Я исправил недочёты: переделал логи на английский язык, вынес в файле pom.xml
 номера версий зависимостей в properties блок, вынес повторяющиеся блоки кода в отдельные методы в коммите: 1e9233afbfc3d8ea00d4076d77aec1091a071286

2023-08-16 17:06 UTC, TyutterinYakov reviewed
Добрый вечер! Отметил оставшиеся недочеты) Хорошего вечера! Если возникнут вопросы - пиши в пачку, буду рад помочь🌃

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +	@Past (message = "Дата рождения не должна быть в будущем")
Для валидации даты рождения есть более подходящая аннотация -  `@PastOrPresent`, но она должна использовать в связке с `@NotNull`, так как она допускает `null` за корректное значение)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/utils/GsonUtils.java
> +	public static Gson getGson() {
Так же можно было бы упростить внедрение, если потребуется использовать `Gson` в разных классах и, чтобы не плодить лишние объекты можно: 
Объявить в классе `FilmorateApplication` метод:
```
    @Bean
    public Gson getGson() {
        return new GsonBuilder().registerTypeAdapter(LocalDate.class, new CustomLocalDateAdapter().nullSafe()).create();
    }
```

А там, где он потребуется, произвести внедрение через параметры конструктора) Например:

```
private final Gson gson;

public UserController(Gson gson) {
    this.gson = gson;
}
```

2023-08-16 17:06 UTC, TyutterinYakov commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
(предложение)  Кстати, тестирование валидации с помощью аннотаций должно осуществляться подобным образом
https://stackoverflow.com/questions/29069956/how-to-test-validation-annotations-of-a-class-using-junit

Но вообще, можно использовать моки, но эта тема будет разобрана немного позже, но, если будет интересно https://spring.io/guides/gs/testing-web/

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getName().isBlank()) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getDescription().length() > 200) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28", DateUtils.formatter))) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getDuration() < 0) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (user.getLogin().isBlank() || user.getLogin().contains(" ")) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (user.getBirthday().isAfter(LocalDate.now())) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-16 17:06 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +	private String login;
(предложение)Также строка не может содержать пробелов - для этой цели было бы удобно использовать аннотацию `@Pattern`
https://www.geeksforgeeks.org/spring-mvc-regular-expression-validation/

2023-08-17 15:55 UTC, FisanovE commented
Изменил описание проекта в pom.xml, переделал валидацию сущностей через аннотации, изменил тесты для проверки валидации, уточнил и дополнил аннотации, изменил наследование в исключении на RuntimeExceprtion, перенёс сборку Gson в класс FilmorateApplication. Коммит https://github.com/FisanovE/java-filmorate/pull/6/commits/02dc6562ab6a6c86977195139730ac15a2d61136

2023-08-17 18:20 UTC, TyutterinYakov reviewed
Добрый вечер) Кажется на прошлой итерации ты раскрыл список не всех замечаний)  их повторно продублировал и отметил некоторые новые предложения) Хорошего вечера! Если возникнут вопросы - пиши в пачку, буду рад помочь🌃

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +	private String login;
Не забываем использовать `@NotNull`, так как аннотация `@Pattern` допускает это значение за корректное)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getName().isBlank()) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getDescription().length() > 200) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getReleaseDate().isBefore(LocalDate.parse("1895-12-28", DateUtils.formatter))) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		if (film.getDuration() < 0) {
Эта проверка уже реализована с помощью аннотации валидации, следовательно она не требуется) О том, как тестировать такой вид валидации описал в одном из классов с тестами)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		for (User currentUser : users.values()) {
Также следует добавить `&& !Objects.equals(currentUser.getId(), user.getId())` 
Иначе при обновлении может возникнуть ситуация, когда мы выбросим исключение из-за обновляемого пользователя, хотя старая запись будет заменена)
Также хорошо было бы вынести эту логику в отдельный приватный метод, так как тогда следует использовать ее при создании, так как там тоже важно будет поддерживать уникальность)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +			if (currentFilm.getName().equals(film.getName()) && currentFilm.getReleaseDate()
Также следует добавить `&& !Objects.equals(currentFilm.getId(), film.getId())` 
Иначе при обновлении может возникнуть ситуация, когда мы выбросим исключение из-за обновляемого фильма, хотя старая запись будет заменена)
Также хорошо было бы вынести эту логику в отдельный приватный метод, так как тогда следует использовать ее при создании, так как там тоже важно будет поддерживать уникальность)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		return films.get(film.getId());
Так как мы работаем с ссылкой на объект, можно было бы не производить повторное обращение к мапе, а сразу же вернуть результат:
`return film;`
Так как ссылку на этот объект мы уже и положили в мапу)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +		return films.get(film.getId());
Так как мы работаем с ссылкой на объект, можно было бы не производить повторное обращение к мапе, а сразу же вернуть результат:
`return film;`
Так как ссылку на этот объект мы уже и положили в мапу)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		return users.get(user.getId());
Так как мы работаем с ссылкой на объект, можно было бы не производить повторное обращение к мапе, а сразу же вернуть результат:
`return user;`
Так как ссылку на этот объект мы уже и положили в мапу)

2023-08-17 18:20 UTC, TyutterinYakov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		return users.get(user.getId());
Так как мы работаем с ссылкой на объект, можно было бы не производить повторное обращение к мапе, а сразу же вернуть результат:
`return user;`
Так как ссылку на этот объект мы уже и положили в мапу)

2023-08-18 04:35 UTC, FisanovE commented
Уточнил проверку объектов на повторы, вынес код проверки в отдельный метод, уточнил аннотации валидации полей объектов, удалил не используемые методы. Коммит https://github.com/FisanovE/java-filmorate/pull/6/commits/f474e377dae99d16918d3be77dd17849ab26b292

2023-08-28 09:08 UTC, merged