feat: создать storage-классы и интерфейсы и перенести туда всю логику…
FisanovE/java-filmorate pull request #7
Opened 2023-09-03 11:05 UTC by FisanovE

… хранения, обновления и поиска объектов. Добавить service-классы и реализовать функции добавления друзей и лайков. Добавить внедрение зависимостей.

2023-09-04 05:10 UTC, krylov-sergey-sergeevich requested changes
Привет, есть моменты давай их обсудим =)

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  		log.info("Received request to endpoint: POST /films");
Received request to endpoint: - слишком длинно, можно проще
Endpoint -> Create film
Endpoint -> Get films

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (id1.equals(friendId)) {
Я бы эту логику оставил бы в сервисе, вдруг кто-то попытается воспользоваться сервисом неправильно а там этой проверки нет

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +	private HashSet<Long> friends;
Можно лучше: private Set<Long> friendIds = new HashSet<>();

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +	InMemoryFilmStorage filmStorage;
Модификатор доступа и зачем нам конструктор когда есть ломбок?

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Не могу найти валидацию, в контроллере и в сервисе не вижу. Подскажи если упускаю что-то подобное ищу:
```
	void validate(Film data) {
		if (data.getName() == null || data.getName().isEmpty()) {
			throw new ValidationException("Film name invalid");
		}
		if (data.getDescription() != null && data.getDescription().length() > MAX_NAME_SIZE) {
			throw new ValidationException("Film description invalid");
		}
		if (data.getReleaseDate() == null || data.getReleaseDate().isBefore(FILM_BIRTHDAY)) {
			throw new ValidationException("Film release date invalid");
		}
		if (data.getDuration() <= 0) {
			throw new ValidationException("Film duration invalid");
		}
	}
```

2023-09-04 05:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +	private void checkingRepeat(Map<Long, User> users, User user) {
Не до конца понятен смысл метода, давай улучшим его стилистику

2023-09-04 10:12 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Валидацию в контроллерах делал в прошлом ФП. Но тогда же, после ревью перенёс её в модели и сделал через аннотации.

`public class Film {
	private Long id;

	@NotBlank (message = "Film title must not be empty")
	private String name;

	@NotNull
	@Size (max = 200, message = "The maximum description length is 200 characters")
	private String description;

	@DateIsAfter
	private LocalDate releaseDate;

	@Positive (message = "The duration of the film should be positive")
	private int duration;

	private Set<Long> likedUsersIds = new HashSet<>();
}`

2023-09-04 10:18 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  		log.info("Received request to endpoint: POST /films");
Откорректировал.

2023-09-04 10:20 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +		if (id1.equals(friendId)) {
Проверку на добавление самого себя в друзья перенёс в сервис.

2023-09-04 10:21 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +	private HashSet<Long> friends;
Исправил.

2023-09-04 10:21 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +	InMemoryFilmStorage filmStorage;
Добавил модификаторы доступа, убрал лишний конструктор.

2023-09-04 10:30 UTC, FisanovE commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +	private void checkingRepeat(Map<Long, User> users, User user) {
Этот метод для проверки, зарегистрирован ли уже email нового пользователя. Не особо понимаю, как его улучшить. Может код из него просто вставить в тот метод, где он будет использоваться? Он используется всего 2 раза, но я его вынес в отдельный метод, чтобы не было повторов.

2023-09-05 05:32 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
Это не совсем хорошо тк проверка по сути будет уже "на конечном" этапе, а желательно ее делать сразу как получили запрос и проверяем корректный ли запрос

2023-09-05 05:35 UTC, krylov-sergey-sergeevich requested changes
Привет, есть два вопроса
- валидация
- метод для email
Давай их обсудим докрутим и будет зачет =)

2023-09-05 05:35 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +			if (Objects.equals(currentUser.getEmail(), user.getEmail()) && !users.containsKey(user.getId())) {
вижу что не изменилось, нет идей? Если что пиши в пачке

2023-09-11 05:29 UTC, krylov-sergey-sergeevich approved these changes
Привет, зачет

2023-09-12 13:12 UTC, merged